### ISSUE TITLE
Understanding the Reference App - Analytics flow.

### ISSUE THREAD

**Issue by ProgramErgoSum** [PredixDev/rmd-analytics#1]
This is about the first graphic in the documentation.
1. Step 1 shows data arriving at a web sockets server. Is the web sockets server limited to only this application? If not, does Predix PaaS have life-cycle methods to control end-points (connected by devices)?
2. Step 3 triggers analytics. How? What's the condition? How can I control the trigger?
3. Is RMD Orchestration _a particular_ BPMN based business process run by Predix Orchestration Engine? Does the RMD Orchestration run on incoming data?
4. What is the Predix Analytic Engine? Does it orchestrate Analytic 1, 2, 3 ... _N_?
5. If I have prepared an Anomaly Detection module in R, will this be a certain Analytic (1 to _N_)?

**Comment by turnerth** [comment]
1. We have the WebSocket server, which we sometimes use for sending data from Predix Machine to the RefApp UI.  https://github.com/PredixDev/predix-websocket-server.  You can find some examples and tutorials showing how to send websocket data from Predix Machine.
2. We aren't yet putting messages on queues when data arrives.  Just a time and resource issue, since we've been building the tutorials site.  The trigger is a FieldChangedEvent.  We put this message on the queue to trigger an orchestration. See the[ rmd-orchestration](https://github.com/predixdev/rmd-orchestration/tree/587361ecddaf23f35a8cdeffa39928e463d18f51) project
   { "fieldChangedList": { "fieldChanged": [{ "solutionIdentifier": { "@type": "SolutionIdentifier", "id": 2, "name": "WaterRMD123" }, "assetList": { "asset": [{ "assetIdFieldIdentifier": { "@type": "FieldIdentifier", "id": 5, "name": "assetId" } }] }, "fieldIdentifierValueList": { "fieldIdentifierValue": [{ "fieldIdentifier": { "@type": "FieldIdentifier", "id": 81, "name": "Reported Distance" } }] }, "timeChanged": 1347347773000, "externalAttributeMap": { "entry": [{}] } }] } }
3. rmd-orchestration runs a sample bpmn file stored in src/main/resources (I believe).  Yes,  it runs based on what's in the FieldChangedEvent.
4. Yes, it is a BPMN engine.  Each rectangle in the BPMN is a Service Task.  The Service in this case is the URL of your analytic.  It is essentially a URL invoker.
5. Yes, it would a certain analytic represented by your URL.  If you use the Analytic Catalog to deploy your Analytic it will know of the URL.  So the BPMN just needs the uniqueId of your analytic and it will ask the Catalog for the URL.

**Comment by ProgramErgoSum** [comment]
Is the Predix Machine hard-wired to communicate with WebSockets only?

**Comment by gstroup** [comment]
No, you could use HTTP or other methods if you like.  You could write some Java code to run in Predix Machine and send data however you like.  We recommend web sockets for constantly streaming large amounts of data.

**Comment by ProgramErgoSum** [comment]
Thanks!

One thing is clear. You guys are very quick to respond!

Can't wait to do some cool stuff with Predix. I do have an account; just
waiting for a good idea. :)

Pardon brevity, typos and grammar mistakes. Sent from phone.
